name: Sincronizar Repo con Google Drive

on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Empaquetar repositorio en ZIP
        run: |
          zip -r repositorio_develop.zip . -x "*.git*"

      - name: Subir a Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.3.5
        with:
          target: "repositorio_develop.zip"
          credentials: ${{ secrets.GDRIVE_SA_KEY }}
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
          override: true
